require_relative '../lib/fprinter'
# FPrinter.bold("This is a bold print test")
# FPrinter.blink("This is a blink print test")
# FPrinter.underline("This is a undelined print test")
# FPrinter.highlight("This is a highlighted print test")
# FPrinter.black("This is a black print test")
# FPrinter.red("This is a red print test")
# FPrinter.green("This is a green print test")
# FPrinter.yellow("This is a yellow print test")
# FPrinter.blue("This is a blue print test")
# FPrinter.magenta("This is a magenta print test")
# FPrinter.cyan("This is a cyan print test")
# FPrinter.white("This is a black print test")
# FPrinter.highlighted_red("This is a red print test")
# FPrinter.highlighted_green("This is a green print test")
# FPrinter.highlighted_yellow("This is a yellow print test")
# FPrinter.highlighted_blue("This is a blue print test")
# FPrinter.highlighted_magenta("This is a magenta print test")
# FPrinter.highlighted_cyan("This is a cyan print test")
# FPrinter.highlighted_white("This is a white print test")
# FPrinter.slow("This is a slowprint test")
# FPrinter.slow_unprint("This is an unprint test, read it fast, or it will disapear")
# FPrinter.reverse("This is a reverse print test, you'll see the beginning only at the end")
# FPrinter.appear_from_left("This is a print test which appear from the left")
# FPrinter.appear_from_right("This is a print test which appear from the left")
# FPrinter.big("This is big")
