# Printer.bold("This is a bold print test")
# Printer.blink("This is a blink print test")
# Printer.underline("This is a undelined print test")
# Printer.highlight("This is a highlighted print test")
# Printer.black("This is a black print test")
# Printer.red("This is a red print test")
# Printer.green("This is a green print test")
# Printer.yellow("This is a yellow print test")
# Printer.blue("This is a blue print test")
# Printer.magenta("This is a magenta print test")
# Printer.cyan("This is a cyan print test")
# Printer.white("This is a black print test")
# Printer.highlighted_red("This is a red print test")
# Printer.highlighted_green("This is a green print test")
# Printer.highlighted_yellow("This is a yellow print test")
# Printer.highlighted_blue("This is a blue print test")
# Printer.highlighted_magenta("This is a magenta print test")
# Printer.highlighted_cyan("This is a cyan print test")
# Printer.highlighted_white("This is a white print test")
# Printer.slow("This is a slowprint test")
# Printer.slow_unprint("This is an unprint test, read it fast, or it will disapear")
# Printer.reverse("This is a reverse print test, you'll see the beginning only at the end")
# Printer.appear_from_left("This is a print test which appear from the left")
# Printer.appear_from_right("This is a print test which appear from the left")
# Printer.big("This is big")
